[tool.poetry]
name = "cutting-tools"
version = "0.1.3"
description = ""
authors = ["Andrey Nikolaevich Korenyuk <korenyuk.a.n@mail.ru>"]
readme = "README.md"
packages = [{include = "cutting_tools"}]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.5.1"
openpyxl = "^3.0.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
