[tool.poetry]
name = "cutting-tools"
version = "0.1.37"
description = ""
authors = ["Andrey Nikolaevich Korenyuk <korenyuk.a.n@mail.ru>"]
readme = "README.md"
packages = [{include = "cutting_tools"}]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.5.1"
openpyxl = "^3.0.10"
dependency-injector = "^4.41.0"
logger = {path = "I:/Программирование/Pro0.5-logger_for_my_projects/dist/logger-0.1.4.tar.gz"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

