"""fix_autoincrement_in_geometry_tables

Revision ID: 2e29c7d4a9fd
Revises: 327142e45843
Create Date: 2025-06-22 20:14:02.453275

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2e29c7d4a9fd'
down_revision: Union[str, None] = '327142e45843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Создаем последовательность для geometry_milling_cutters.id если её нет
    op.execute("CREATE SEQUENCE IF NOT EXISTS geometry_milling_cutters_id_seq")

    # Устанавливаем последовательность как значение по умолчанию для id
    op.execute(
        "ALTER TABLE geometry_milling_cutters ALTER COLUMN id SET DEFAULT nextval('geometry_milling_cutters_id_seq')"
    )

    # Устанавливаем последовательность как владельца колонки id
    op.execute("ALTER SEQUENCE geometry_milling_cutters_id_seq OWNED BY geometry_milling_cutters.id")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
