"""change_id_structure_in_geometry_tables

Revision ID: 327142e45843
Revises: 4084fb1fe5d9
Create Date: 2025-06-22 19:57:50.211065

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '327142e45843'
down_revision: Union[str, None] = '4084fb1fe5d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Создаем новую таблицу geometry_drilling_cutter
    op.create_table(
        'geometry_drilling_cutter',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tool_id', sa.Integer(), nullable=False),
        sa.Column('a_', sa.Float(), nullable=True),
        sa.Column('D', sa.Float(), nullable=True),
        sa.Column('d_1_', sa.Float(), nullable=True),
        sa.Column('d_2_', sa.Float(), nullable=True),
        sa.Column('l_', sa.Float(), nullable=True),
        sa.Column('L', sa.Float(), nullable=True),
        sa.Column('f_', sa.Float(), nullable=True),
        sa.Column('z', sa.Integer(), nullable=True),
        sa.Column('morse_taper', sa.String(length=50), nullable=True),
        sa.Column('execution', sa.String(length=100), nullable=True),
        sa.Column('fi_', sa.Float(), nullable=True),
        sa.Column('group', sa.String(length=100), nullable=True),
        sa.Column('D_1', sa.Float(), nullable=True),
        sa.Column('P', sa.Float(), nullable=True),
        sa.Column('d_', sa.Float(), nullable=True),
        sa.Column('direction', sa.String(length=100), nullable=True),
        sa.Column('B', sa.Float(), nullable=True),
        sa.Column('K', sa.Float(), nullable=True),
        sa.Column('accuracy', sa.String(length=100), nullable=True),
        sa.Column('D_2', sa.Float(), nullable=True),
        sa.Column('l_1_', sa.Float(), nullable=True),
        sa.Column('series', sa.String(length=100), nullable=True),
        sa.Column('omega_', sa.Float(), nullable=True),
        sa.Column('r_', sa.Float(), nullable=True),
        sa.Column('D_nominal', sa.Float(), nullable=True),
        sa.Column('D_1_additional', sa.Float(), nullable=True),
        sa.Column('D_2_additional', sa.Float(), nullable=True),
        sa.Column('L_1', sa.Float(), nullable=True),
        sa.Column('L_2', sa.Float(), nullable=True),
        sa.Column('L_3', sa.Float(), nullable=True),
        sa.Column('L_3_additional', sa.Float(), nullable=True),
        sa.Column('rank', sa.String(length=100), nullable=True),
        sa.Column('shank_type', sa.String(length=100), nullable=True),
        sa.Column('l_deviation', sa.Float(), nullable=True),
        sa.Column('L_deviation', sa.Float(), nullable=True),
        sa.Column('r_deviation', sa.Float(), nullable=True),
        sa.Column('l_0_', sa.Float(), nullable=True),
        sa.Column('k_', sa.Float(), nullable=True),
        sa.Column('K_deviation', sa.Float(), nullable=True),
        sa.Column('a_deviation', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(
            ['tool_id'],
            ['tools.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_geometry_drilling_cutter_id'), 'geometry_drilling_cutter', ['id'], unique=False)
    op.create_index(op.f('ix_geometry_drilling_cutter_tool_id'), 'geometry_drilling_cutter', ['tool_id'], unique=True)

    # 2. Добавляем колонку tool_id в geometry_milling_cutters (сначала nullable)
    op.add_column('geometry_milling_cutters', sa.Column('tool_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_geometry_milling_cutters_tool_id'), 'geometry_milling_cutters', ['tool_id'], unique=False)

    # 3. Копируем данные: устанавливаем tool_id = id для существующих записей
    op.execute("UPDATE geometry_milling_cutters SET tool_id = id")

    # 4. Делаем tool_id NOT NULL
    op.alter_column('geometry_milling_cutters', 'tool_id', nullable=False)

    # 5. Удаляем старую связь по id
    op.drop_constraint(op.f('geometry_milling_cutters_id_fkey'), 'geometry_milling_cutters', type_='foreignkey')

    # 6. Создаем новую связь по tool_id
    op.create_foreign_key(None, 'geometry_milling_cutters', 'tools', ['tool_id'], ['id'])

    # 7. Делаем tool_id уникальным
    op.drop_index(op.f('ix_geometry_milling_cutters_tool_id'), table_name='geometry_milling_cutters')
    op.create_index(op.f('ix_geometry_milling_cutters_tool_id'), 'geometry_milling_cutters', ['tool_id'], unique=True)

    # 8. Удаляем колонки tool_type и standard (они есть в таблице tools)
    op.drop_column('geometry_milling_cutters', 'tool_type')
    op.drop_column('geometry_milling_cutters', 'standard')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Восстанавливаем колонки tool_type и standard
    op.add_column(
        'geometry_milling_cutters', sa.Column('standard', sa.VARCHAR(length=100), autoincrement=False, nullable=True)
    )
    op.add_column(
        'geometry_milling_cutters', sa.Column('tool_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True)
    )

    # 2. Удаляем новую связь по tool_id
    op.drop_constraint(None, 'geometry_milling_cutters', type_='foreignkey')

    # 3. Восстанавливаем старую связь по id
    op.create_foreign_key(op.f('geometry_milling_cutters_id_fkey'), 'geometry_milling_cutters', 'tools', ['id'], ['id'])

    # 4. Удаляем колонку tool_id
    op.drop_index(op.f('ix_geometry_milling_cutters_tool_id'), table_name='geometry_milling_cutters')
    op.drop_column('geometry_milling_cutters', 'tool_id')

    # 5. Удаляем таблицу geometry_drilling_cutter
    op.drop_index(op.f('ix_geometry_drilling_cutter_tool_id'), table_name='geometry_drilling_cutter')
    op.drop_index(op.f('ix_geometry_drilling_cutter_id'), table_name='geometry_drilling_cutter')
    op.drop_table('geometry_drilling_cutter')

    # ### end Alembic commands ###
