"""rename_milling_cutters_to_geometry_frez

Revision ID: 8175dd6166f4
Revises: ea500c0b1417
Create Date: 2025-06-22 17:09:16.015241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8175dd6166f4'
down_revision: Union[str, None] = 'ea500c0b1417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
