"""create_geometry_turning_cutters_table

Revision ID: 921156078d8d
Revises: d96ab5cc4b2e
Create Date: 2025-06-22 21:46:41.380634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '921156078d8d'
down_revision: Union[str, None] = 'd96ab5cc4b2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geometry_turning_cutters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('a_', sa.Float(), nullable=True),
    sa.Column('D', sa.Float(), nullable=True),
    sa.Column('l_', sa.Float(), nullable=True),
    sa.Column('L', sa.Float(), nullable=True),
    sa.Column('execution', sa.String(length=100), nullable=True),
    sa.Column('fi_', sa.Float(), nullable=True),
    sa.Column('mat_', sa.String(length=100), nullable=True),
    sa.Column('group', sa.String(length=100), nullable=True),
    sa.Column('D_1', sa.Float(), nullable=True),
    sa.Column('d_', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(length=100), nullable=True),
    sa.Column('B', sa.Float(), nullable=True),
    sa.Column('h_', sa.Float(), nullable=True),
    sa.Column('l_1_', sa.Float(), nullable=True),
    sa.Column('m_', sa.Float(), nullable=True),
    sa.Column('l_2_', sa.Float(), nullable=True),
    sa.Column('r_', sa.Float(), nullable=True),
    sa.Column('H', sa.Float(), nullable=True),
    sa.Column('fi_1_', sa.Float(), nullable=True),
    sa.Column('gamma_', sa.Float(), nullable=True),
    sa.Column('lambda_', sa.Float(), nullable=True),
    sa.Column('n_', sa.Float(), nullable=True),
    sa.Column('bl_', sa.Float(), nullable=True),
    sa.Column('cutter_type', sa.String(length=100), nullable=True),
    sa.Column('h_1_', sa.Float(), nullable=True),
    sa.Column('cutter_group', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geometry_turning_cutters_id'), 'geometry_turning_cutters', ['id'], unique=False)
    op.create_index(op.f('ix_geometry_turning_cutters_tool_id'), 'geometry_turning_cutters', ['tool_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_geometry_turning_cutters_tool_id'), table_name='geometry_turning_cutters')
    op.drop_index(op.f('ix_geometry_turning_cutters_id'), table_name='geometry_turning_cutters')
    op.drop_table('geometry_turning_cutters')
    # ### end Alembic commands ###
