"""remove_tool_type_and_standard_from_countersinking_cutter

Revision ID: 95f397763f57
Revises: cd180695f18e
Create Date: 2025-06-22 21:04:24.832075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95f397763f57'
down_revision: Union[str, None] = 'cd180695f18e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('geometry_countersinking_cutter', 'standard')
    op.drop_column('geometry_countersinking_cutter', 'tool_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geometry_countersinking_cutter', sa.Column('tool_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('geometry_countersinking_cutter', sa.Column('standard', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
