"""Remove unique constraint from marking

Revision ID: a383d011ff66
Revises: a541c29868da
Create Date: 2025-06-21 16:41:02.271175

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a383d011ff66'
down_revision: Union[str, None] = 'a541c29868da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tools', 'marking', existing_type=sa.VARCHAR(), nullable=True)
    op.drop_constraint(op.f('tools_marking_key'), 'tools', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('tools_marking_key'), 'tools', ['marking'], postgresql_nulls_not_distinct=False)
    op.alter_column('tools', 'marking', existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
