"""create_geometry_countersink_table

Revision ID: cd180695f18e
Revises: 2e29c7d4a9fd
Create Date: 2025-06-22 20:42:39.983078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd180695f18e'
down_revision: Union[str, None] = '2e29c7d4a9fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geometry_countersinking_cutter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('D', sa.Float(), nullable=True),
    sa.Column('l_', sa.Float(), nullable=True),
    sa.Column('L', sa.Float(), nullable=True),
    sa.Column('z', sa.Integer(), nullable=True),
    sa.Column('morse_taper', sa.String(length=50), nullable=True),
    sa.Column('execution', sa.String(length=100), nullable=True),
    sa.Column('fi_', sa.Float(), nullable=True),
    sa.Column('group', sa.String(length=100), nullable=True),
    sa.Column('tool_type', sa.String(length=100), nullable=True),
    sa.Column('standard', sa.String(length=100), nullable=True),
    sa.Column('D_additional', sa.Float(), nullable=True),
    sa.Column('d_', sa.Float(), nullable=True),
    sa.Column('hole_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geometry_countersinking_cutter_id'), 'geometry_countersinking_cutter', ['id'], unique=False)
    op.create_index(op.f('ix_geometry_countersinking_cutter_tool_id'), 'geometry_countersinking_cutter', ['tool_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_geometry_countersinking_cutter_tool_id'), table_name='geometry_countersinking_cutter')
    op.drop_index(op.f('ix_geometry_countersinking_cutter_id'), table_name='geometry_countersinking_cutter')
    op.drop_table('geometry_countersinking_cutter')
    # ### end Alembic commands ###
