"""create_geometry_reamer_table

Revision ID: d96ab5cc4b2e
Revises: 95f397763f57
Create Date: 2025-06-22 21:27:42.543635

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd96ab5cc4b2e'
down_revision: Union[str, None] = '95f397763f57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'geometry_deployment_cutter',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('tool_id', sa.Integer(), nullable=False),
        sa.Column('D', sa.Float(), nullable=True),
        sa.Column('d_1_', sa.Float(), nullable=True),
        sa.Column('d_2_', sa.Float(), nullable=True),
        sa.Column('l_', sa.Float(), nullable=True),
        sa.Column('L', sa.Float(), nullable=True),
        sa.Column('z', sa.Integer(), nullable=True),
        sa.Column('morse_taper', sa.String(length=50), nullable=True),
        sa.Column('execution', sa.String(length=100), nullable=True),
        sa.Column('fi_', sa.Float(), nullable=True),
        sa.Column('mat_', sa.String(length=100), nullable=True),
        sa.Column('group', sa.String(length=100), nullable=True),
        sa.Column('D_1', sa.Float(), nullable=True),
        sa.Column('d_', sa.Float(), nullable=True),
        sa.Column('h_', sa.Float(), nullable=True),
        sa.Column('l_1_', sa.Float(), nullable=True),
        sa.Column('l_2_', sa.Float(), nullable=True),
        sa.Column('r_', sa.Float(), nullable=True),
        sa.Column('l_0_', sa.Float(), nullable=True),
        sa.Column('reamer_type', sa.String(length=100), nullable=True),
        sa.Column('fi_1_', sa.Float(), nullable=True),
        sa.Column('gamma_', sa.Float(), nullable=True),
        sa.Column('lambda_', sa.Float(), nullable=True),
        sa.Column('reamer_taper', sa.Float(), nullable=True),
        sa.Column('d_2_additional', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(
            ['tool_id'],
            ['tools.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_geometry_deployment_cutter_id'), 'geometry_deployment_cutter', ['id'], unique=False)
    op.create_index(
        op.f('ix_geometry_deployment_cutter_tool_id'), 'geometry_deployment_cutter', ['tool_id'], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_geometry_deployment_cutter_tool_id'), table_name='geometry_deployment_cutter')
    op.drop_index(op.f('ix_geometry_deployment_cutter_id'), table_name='geometry_deployment_cutter')
    op.drop_table('geometry_deployment_cutter')
    # ### end Alembic commands ###
