"""change_milling_cutter_id_to_foreign_key

Revision ID: ea500c0b1417
Revises: d70a51754d20
Create Date: 2025-06-21 18:18:48.909767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea500c0b1417'
down_revision: Union[str, None] = 'd70a51754d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_milling_cutters_tool_id'), table_name='milling_cutters')
    op.drop_constraint(op.f('milling_cutters_tool_id_fkey'), 'milling_cutters', type_='foreignkey')
    op.create_foreign_key(None, 'milling_cutters', 'tools', ['id'], ['id'])
    op.drop_column('milling_cutters', 'tool_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milling_cutters', sa.Column('tool_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'milling_cutters', type_='foreignkey')
    op.create_foreign_key(op.f('milling_cutters_tool_id_fkey'), 'milling_cutters', 'tools', ['tool_id'], ['id'])
    op.create_index(op.f('ix_milling_cutters_tool_id'), 'milling_cutters', ['tool_id'], unique=True)
    # ### end Alembic commands ###
